# Numpy Exercises

## Array creation

### Create an array of integers from 1 to 100

In [3]:
import numpy as np

In [9]:
arr = np.arange(1, 101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

### Convert that array into a 2d array

In [10]:
    arr.reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

### using arange() create the following array: 
[5, 10, 15, 20, 25] 

In [11]:
arr = np.arange(5, 26, 5)
arr

array([ 5, 10, 15, 20, 25])

### Create a 4 x 3 array

In [13]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## Random Numbers

### Use Numpy to create a random number between [1 and 100]

In [14]:
np.random.randint(1, 100)

17

### Use Numpy to create a random number between [0 and 1]

In [15]:
np.random.rand()

0.32445564073635536

## Indexing

### Make a row, column and matrix subselection using the following array:
arr_2d = np.arange(1,26).reshape(5,5)

In [7]:
arr = np.arange(1,26).reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
## My Numpy Exercise #1 begin

In [9]:
row = arr[0]

In [10]:
row

array([1, 2, 3, 4, 5])

In [13]:
col = arr[:5, 2]
col

array([ 3,  8, 13, 18, 23])

In [14]:
submat = arr[2:4, 1:3]

In [15]:
submat

array([[12, 13],
       [17, 18]])

In [ ]:
## My Numpy Exercise #1 end

## Array methods

### Using the above array, get the mean of each row

In [17]:
arr.mean(axis = 1)

array([ 3.,  8., 13., 18., 23.])

### Using the above array,  get the mean of each column

In [19]:
arr.mean(axis = 0)

array([11., 12., 13., 14., 15.])

### Using the above array,  get the standard deviation of each column

In [20]:
arr.std(axis = 0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [ ]:
## My Numpy Exercise #2 begin

### Write a function that takes a 2d array and returns the array as standardized values: 
		to standardize a value:   (x - mean)/std

		def standardize(X):
			pass


In [37]:
def standardize(X):
    arr_mean = X.mean(axis = 0)
    arr_std = X.std(axis = 0)
    norm_X = (X - arr_mean)
    print("arr_mean= ", arr_mean, "  arr_std= ", arr_std, "\n")
    print ("normalized_X = \n", norm_X)
    std_X = norm_X / arr_std
    return std_X

In [39]:
s_X = standardize(submat)

arr_mean=  [14.5 15.5]   arr_std=  [2.5 2.5] 

normalized_X = 
 [[-2.5 -2.5]
 [ 2.5  2.5]]


In [40]:
print ("Standardized X values= \n", s_X)

Standardized X values= 
 [[-1. -1.]
 [ 1.  1.]]


In [ ]:
## My Numpy Exercise #2 end